---
- hosts: all

  become: true
  become_method: sudo
  become_user: rdeselle
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
